server:
  port: 8060
spring:
  #  application:
  #    name: device
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lightning?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  session:
    store-type: none

#imooc:
#  security:
#    browser:
#      loginPage: /demo-signIn.html
#关闭security默认配置
#security:
#  basic:
imooc:
  security:
    browser:
      loginType: REDIRECT
    enabled: false
    #图形验证码的长度
    code:
      image:
        length: 6
        width: 100
        url: /user,/user/*